---
env:
  global:
    # DOCKER_EMAIL
    - secure: "NPo7pdmDi/hiQBjUeEjrGi5bmphTzUikXj8BGx1zM0Pzt6f1We4CZjdLtk3jDgmXWTjJfb7C7uYn5MEcWhqsyIspmyX/SinKeqXQejMvOCvOWnLGnJ5eTxIcd+chkurcrSFWGCslamb4LiDjwEVQYCcGAmHpCLebL0z84lkAYx7lZL4+3yDEBQyGhtwExDaknMl6s8MbfcaKZTkhTwvDYWur+3NOXKuHPv9KW3DhQ7DqWbGX82TuFhJRFMGXJcBckRNHU2YhXpopj35/Ep4bOLAaWiDoPBiRVOHXmgbSXOTybKJRk96dUCYojOJDAazTBWtQwwnb2UN+DH2iiMZDF+2jJkFooDwuXAZ0zJ9aW4lZGIC20u9vtZCk6HN76Zn+tUEsLlWwEN9xdxCRYpDm7R1A8fQfgXw59jB7NZz3C+m8iriYp5PAhIFGDJBlq2bF+FHI0AiScWeinghEHZYNr+EOEOxgtA6iN4m6KFVyT/a3zOjxXwdvcfyoKRhJzW3dP3TwNfl1FuYYJQtqEGYdP6YzTiR1FObN3ceM45O8SDsWi5pIgOoPY2oN4NBUamHWLauzjvdqwaRMNNX4Y1uCHXqy0gEqlUvzRr7qH4/OMG89Wb6nw5CkDtOIHmnLAML5/RqHfjggmQRySAw5ny6RNfncgee2LK35fB9ccuLbhX0="
    # DOCKER_USER
    - secure: "viQhXp8DaMdPIGDe+xrXpJ2OCqAhvRj8DyIxF8e10j8STCvO+gvOsAzltDLB0zpVlxMExGLuazkg2b7RyyJX69shSjIhpNrRTOQzjiRJZL3vdFdGm+5xER9/PVVAqVY3lcd8rK2K2ZFTUfSQnfhR2Yfty4RsQ159Yrl3Si56YNuGseGUzlozOH7r0miFN25hpgONFi3vMuXjKGvPFxqa5ROwW3+XHcMif90zT5KajLv7m5Fa1fgMDnXgbG5eeYX/63eQaDc4uAnQeiahso0CIV/n/0H5o85Y4ZSRdnjsuTZKrXWnESEjJaYtK4wPMUxpa3AIoWD8Zte9/Z4lPq2uFWz4arGTtk0So9boNxS7x/jkhGi7Lio7rRKl9anM4v1d0v5mySo1mOBcRF0xxChVSrF8JwbPqWOlYakqMe6cfqPRsn1k/5BqwgIWu9TKthiwDQ3EXMt7iXYqH1VbN2AlgoGA4oRLdPdvw6NLHVYDGEWuGA0KHo1muVxSpy2gADW9Um8kRHSunB8pHp00jgcjrsMfmaG/yqFv8IcW/YAom6D9FtyzxGBxZd91zhjBxfxJwtlYAvEbvGgQhbfzUvazXwBYsRdgHAtCehaGzFwBTkFDDBpagxqfoVt4PAskSam/jIXstBCDymLSdWxB2dbFB/CaCSRhxqMlMKmslqPCTiw="
    # DOCKER_PASS
    - secure: "0Quc8E1tbpePS0RS3BprbjEwcPBGkKXWIF2BvCvlE2dd0Nbij0WyzNhsX0vdP+sA0hdAgtsj7Butd6wGCEQsMy/+93eQUJcrJsfFbuXPYnnwyMhlx4oazo/C5qzey1PkpVJg+sjrXgXcpP59j2CA5jlQDdhgEhUk2HUqKh1Y2Tn+BViZsBdUq1SQGbdcGgB53HxgHvGxh92TEcXc4cQ6OTXHDlnkhNOQAJcwP8/2KCcuVZTnyCKk6TE9Gjo/kpR8QhyopsyVb9lhy1ehXElXPk7uvDU7O8HbWfJsC//8OBQRmpV2CYC9C0iFF3Ia1ddIc/G/cqqaRZQKi63RZrxM5DJ+9jWgDkXk9EYBpiZgNm7kKe7R7B0D63eq1Cs6I3T5AwqwZuMCzQfzQy3zOeO1I++hkpadyfJvkOxfJ7tpFbuoBDnFKwoB5/k+PSropz/7069Mrzp/hzUCYtAoIZDQEToBX5R80w5cr1FTKbsvUfVxffZnfWMyu9KNWKK5Eegisd01s0O/XjYZqounS1Zh1JBIimBo6d15ChIxSEdb4ltp+DwOmd8Unh1bjlYcEYjyyqSqWb+nVbVpNa83E068VqyvsG7ERRN2JBcmG5jzlHAHZ44l6L9Xw77PYKuzIJ4vN4ch/dmRIp+Mq/A+FTRaUrAPASsTBStzgVyCJ8UlfnU="
    - DOCKER_REPO=spreadspace/flumotion

script:
  ### pull current images to potentially use docker build cache
  - docker pull $DOCKER_REPO:base
  - docker pull $DOCKER_REPO:manager
  - docker pull $DOCKER_REPO:worker
  - docker pull $DOCKER_REPO:admin
  ### build the new images
  - docker build -t $DOCKER_REPO:base .
  - docker tag $DOCKER_REPO:base $DOCKER_REPO:base-$TRAVIS_BUILD_NUMBER
  - docker build -t $DOCKER_REPO:manager manager/
  - docker tag $DOCKER_REPO:manager $DOCKER_REPO:manager-$TRAVIS_BUILD_NUMBER
  - docker build -t $DOCKER_REPO:worker worker/
  - docker tag $DOCKER_REPO:worker $DOCKER_REPO:worker-$TRAVIS_BUILD_NUMBER
  - docker build -t $DOCKER_REPO:admin admin/
  - docker tag $DOCKER_REPO:admin $DOCKER_REPO:admin-$TRAVIS_BUILD_NUMBER
  ### push to docker-hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_REPO:base-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO:base
  - docker push $DOCKER_REPO:manager-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO:manager
  - docker push $DOCKER_REPO:worker-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO:worker
  - docker push $DOCKER_REPO:admin-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO:admin
