#!/bin/bash

BASE_D=$(realpath "${BASH_SOURCE%/*}")
VOLUMES_D="$BASE_D/volumes/manager"

HOME_D="$VOLUMES_D/home"
mkdir -p "$HOME_D"

exec sudo docker run --rm -it -v "$HOME_D:/srv" spreadspace/flumotion manager $@
