#!/bin/bash

BASE_D=$(realpath "${BASH_SOURCE%/*}")
VOLUMES_D="$BASE_D/volumes/worker"

HOME_D="$VOLUMES_D/home"
mkdir -p "$HOME_D"
sudo chown 998:998 "$HOME_D"

exec sudo docker run --rm -it -v "$HOME_D:/srv" -p 8000:8000 spreadspace/flumotion:worker worker $@
